// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: patient/proto/patient.proto

package patientpb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Dosage) Validate() error {
	return nil
}
func (this *Prescription) Validate() error {
	if this.PrescribedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PrescribedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PrescribedAt", err)
		}
	}
	if this.Dosage != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Dosage); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Dosage", err)
		}
	}
	return nil
}
func (this *Patient) Validate() error {
	for _, item := range this.Prescriptions {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Prescriptions", err)
			}
		}
	}
	return nil
}
func (this *GetPatientRequest) Validate() error {
	if this.Id == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must not be an empty string`, this.Id))
	}
	return nil
}
func (this *GetPatientResponse) Validate() error {
	if this.Patient != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Patient); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Patient", err)
		}
	}
	return nil
}
func (this *CreatePatientRequest) Validate() error {
	if this.Name == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must not be an empty string`, this.Name))
	}
	return nil
}
func (this *CreatePatientResponse) Validate() error {
	if this.Patient != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Patient); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Patient", err)
		}
	}
	return nil
}
func (this *PrescribeRequest) Validate() error {
	if this.PatientId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("PatientId", fmt.Errorf(`value '%v' must not be an empty string`, this.PatientId))
	}
	if this.MedicineId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("MedicineId", fmt.Errorf(`value '%v' must not be an empty string`, this.MedicineId))
	}
	if this.DoctorId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("DoctorId", fmt.Errorf(`value '%v' must not be an empty string`, this.DoctorId))
	}
	if nil == this.Dosage {
		return github_com_mwitkow_go_proto_validators.FieldError("Dosage", fmt.Errorf("message must exist"))
	}
	if this.Dosage != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Dosage); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Dosage", err)
		}
	}
	return nil
}
func (this *PrescribeResponse) Validate() error {
	if this.Patient != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Patient); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Patient", err)
		}
	}
	return nil
}
